# fly.toml app configuration file generated for mangaflow-api on 2023-10-09T12:47:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mangaflow-api"
primary_region = "qro"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
